const fs = require('fs');

const decemberHTML = [
  '        <details class="campaign-item" style="border-left: 4px solid #DB2777;">',
  '          <summary>',
  '            <div>',
  '              <span class="campaign-status status-active" style="background: #FCE7F3; color: #BE185D;">Temporada 5</span>',
  '              <strong>Dezembro 2026: O ANO EM QUE O FISCAL DECIDE O FUTURO</strong>',
  '            </div>',
  '            <p>Planejamento, aprendizado de 2026 e preparação para 2027.</p>',
  '          </summary>',
  '          <div class="campaign-content" style="background: #F8FAFC; border-radius: 8px; padding: 20px; margin-top: 16px; border: 1px solid #E2E8F0;">',
  '            <div style="background: #FFFFFF; padding: 16px; border-radius: 8px; border-left: 4px solid #BE185D; margin-bottom: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">',
  '              <h4 style="margin-top:0; color:#1E293B; display:flex; align-items:center; gap:8px;">',
  '                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#BE185D" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>',
  '                Manifesto de Marca SAAM',
  '              </h4>',
  '              <p style="font-size: 15px; font-style: italic; color:#334155; line-height:1.6; margin-bottom:0;">',
  '                "As empresas que liderarão 2027 não serão as que mais trabalharam em 2026. Serão as que melhor aprenderam com 2026. O futuro não é construído em janeiro. Ele começa nas decisões tomadas antes do ano virar."',
  '              </p>',
  '            </div>',
  '            ',
  '            <h4 style="color: #0F172A; border-bottom: 2px solid #E2E8F0; padding-bottom: 8px; margin-top: 24px;">Objetivo Estratégico</h4>',
  '            <p style="font-size: 14px; color: #475569; line-height: 1.6;">',
  '              A SAAM encerra 2026 posicionada como uma marca que guia a evolução do profissional fiscal. Dezembro não é o fim, é o primeiro mês de 2027. O foco é <strong>planejamento, revisão e vantagem competitiva</strong>.',
  '            </p>',
  '',
  '            <h4 style="color: #0F172A; border-bottom: 2px solid #E2E8F0; padding-bottom: 8px; margin-top: 24px;">A Mudança de Percepção Desejada</h4>',
  '            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-top: 16px;">',
  '              <div style="background: #FEF2F2; padding: 16px; border-radius: 8px; border: 1px solid #FCA5A5;">',
  '                <h5 style="color: #B91C1C; margin-top: 0; margin-bottom: 12px; display: flex; align-items: center; gap: 6px;">',
  '                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>',
  '                  De (O Mercado Pensa Hoje)',
  '                </h5>',
  '                <ul style="margin: 0; padding-left: 20px; font-size: 13px; color: #7F1D1D; line-height: 1.6;">',
  '                  <li>Dezembro é só fechamento.</li>',
  '                  <li>Janeiro começamos de novo.</li>',
  '                  <li>Planejamento pode esperar.</li>',
  '                </ul>',
  '              </div>',
  '              <div style="background: #F0FDF4; padding: 16px; border-radius: 8px; border: 1px solid #86EFAC;">',
  '                <h5 style="color: #15803D; margin-top: 0; margin-bottom: 12px; display: flex; align-items: center; gap: 6px;">',
  '                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>',
  '                  Para (Com a SAAM)',
  '                </h5>',
  '                <ul style="margin: 0; padding-left: 20px; font-size: 13px; color: #166534; line-height: 1.6;">',
  '                  <li>Dezembro é planejamento.</li>',
  '                  <li>Grandes resultados começam antes do novo ano.</li>',
  '                  <li>A preparação vale mais que a reação.</li>',
  '                </ul>',
  '              </div>',
  '            </div>',
  '',
  '            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin-top: 24px;">',
  '              <div>',
  '                <h4 style="color: #0F172A; border-bottom: 2px solid #E2E8F0; padding-bottom: 8px;">Nova Propriedade Intelectual</h4>',
  '                <div style="background: #FDF2F8; padding: 16px; border-radius: 8px; border: 1px solid #FBCFE8;">',
  '                  <h5 style="color: #BE185D; margin-top: 0;">PLANO FISCAL 2027 SAAM</h5>',
  '                  <ul style="padding-left: 20px; margin-bottom: 0; font-size: 13px; color: #9D174D;">',
  '                    <li><strong>1. Revisar:</strong> Tudo o que aconteceu em 2026.</li>',
  '                    <li><strong>2. Aprender:</strong> Quais processos falharam.</li>',
  '                    <li><strong>3. Planejar:</strong> Novos indicadores.</li>',
  '                    <li><strong>4. Automatizar:</strong> Eliminar gargalos.</li>',
  '                    <li><strong>5. Evoluir:</strong> Começar 2027 em um nível superior.</li>',
  '                  </ul>',
  '                </div>',
  '                <h4 style="color: #0F172A; border-bottom: 2px solid #E2E8F0; padding-bottom: 8px; margin-top: 16px;">Grande Campanha</h4>',
  '                <p style="font-size: 13px; color: #475569;"><strong>OPERAÇÃO 2027</strong>: Uma campanha de 30 dias que convida o público a preparar o próximo ano com pequenos passos diários.</p>',
  '              </div>',
  '              ',
  '              <div>',
  '                <h4 style="color: #0F172A; border-bottom: 2px solid #E2E8F0; padding-bottom: 8px;">A Jornada de Dezembro</h4>',
  '                <ul style="list-style-type: none; padding: 0; font-size: 14px; color: #475569;">',
  '                  <li style="margin-bottom: 8px;"><strong>Capítulo 1: O Que 2026 Ensinou</strong></li>',
  '                  <li style="margin-bottom: 8px;"><strong>Capítulo 2: O Que Precisa Mudar</strong></li>',
  '                  <li style="margin-bottom: 8px;"><strong>Capítulo 3: Planejando 2027</strong></li>',
  '                  <li><strong>Capítulo 4: O Futuro Começa Agora</strong></li>',
  '                </ul>',
  '                ',
  '                <h4 style="color: #0F172A; border-bottom: 2px solid #E2E8F0; padding-bottom: 8px; margin-top: 16px;">Séries Fixas</h4>',
  '                <div style="display: flex; flex-wrap: wrap; gap: 8px;">',
  '                  <span style="background: #E2E8F0; padding: 4px 10px; border-radius: 4px; font-size: 11px; font-weight: 700; color: #475569;">Retrospectiva Inteligente</span>',
  '                  <span style="background: #E2E8F0; padding: 4px 10px; border-radius: 4px; font-size: 11px; font-weight: 700; color: #475569;">Checklist 2027</span>',
  '                  <span style="background: #E2E8F0; padding: 4px 10px; border-radius: 4px; font-size: 11px; font-weight: 700; color: #475569;">Meta da Semana</span>',
  '                </div>',
  '              </div>',
  '            </div>',
  '            ',
  '          </div>',
  '        </details>'
].join('\\n');

let html = fs.readFileSync('index.html', 'utf-8');

const blockToFind = /<strong>Novembro 2026: O FISCAL QUE ANTECIPA O FUTURO<\/strong>[\s\S]*?<\/details>/;
const match = html.match(blockToFind);
if (match) {
    html = html.replace(match[0], match[0] + '\\n' + decemberHTML);
    fs.writeFileSync('index.html', html, 'utf-8');
    console.log('December campaign injected successfully into index.html');
} else {
    console.log('Could not find November block to append to.');
}
