const fs = require('fs');

const novemberHTML = [
  '        <details class="campaign-item" style="border-left: 4px solid #6366F1;">',
  '          <summary>',
  '            <div>',
  '              <span class="campaign-status status-active" style="background: #E0E7FF; color: #4338CA;">Temporada 4</span>',
  '              <strong>Novembro 2026: O FISCAL QUE ANTECIPA O FUTURO</strong>',
  '            </div>',
  '            <p>Previsibilidade, governança e antecipação de riscos.</p>',
  '          </summary>',
  '          <div class="campaign-content" style="background: #F8FAFC; border-radius: 8px; padding: 20px; margin-top: 16px; border: 1px solid #E2E8F0;">',
  '            <div style="background: #FFFFFF; padding: 16px; border-radius: 8px; border-left: 4px solid #4338CA; margin-bottom: 20px; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">',
  '              <h4 style="margin-top:0; color:#1E293B; display:flex; align-items:center; gap:8px;">',
  '                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#4338CA" stroke-width="2"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>',
  '                Manifesto de Marca SAAM',
  '              </h4>',
  '              <p style="font-size: 15px; font-style: italic; color:#334155; line-height:1.6; margin-bottom:0;">',
  '                "As melhores empresas não reagem aos problemas. Elas os antecipam. O futuro pertence às empresas que conseguem enxergar antes da inconsistência, antes da multa, antes da rejeição."',
  '              </p>',
  '            </div>',
  '            ',
  '            <h4 style="color: #0F172A; border-bottom: 2px solid #E2E8F0; padding-bottom: 8px; margin-top: 24px;">Objetivo Estratégico</h4>',
  '            <p style="font-size: 14px; color: #475569; line-height: 1.6;">',
  '              Posicionar a SAAM como a empresa que ajuda organizações a antecipar riscos, criar processos resilientes e tomar decisões com segurança. O Fiscal deixa de ser uma área reativa e passa a ser uma área de <strong>previsibilidade, governança e estratégia</strong>.',
  '            </p>',
  '',
  '            <h4 style="color: #0F172A; border-bottom: 2px solid #E2E8F0; padding-bottom: 8px; margin-top: 24px;">A Mudança de Percepção Desejada</h4>',
  '            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-top: 16px;">',
  '              <div style="background: #FEF2F2; padding: 16px; border-radius: 8px; border: 1px solid #FCA5A5;">',
  '                <h5 style="color: #B91C1C; margin-top: 0; margin-bottom: 12px; display: flex; align-items: center; gap: 6px;">',
  '                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>',
  '                  De (O Mercado Pensa Hoje)',
  '                </h5>',
  '                <ul style="margin: 0; padding-left: 20px; font-size: 13px; color: #7F1D1D; line-height: 1.6;">',
  '                  <li>Auditoria encontra erros.</li>',
  '                  <li>Compliance evita multas.</li>',
  '                  <li>Governança é burocracia.</li>',
  '                  <li>O Fiscal reage aos problemas.</li>',
  '                  <li>Risco faz parte da operação.</li>',
  '                </ul>',
  '              </div>',
  '              <div style="background: #F0FDF4; padding: 16px; border-radius: 8px; border: 1px solid #86EFAC;">',
  '                <h5 style="color: #15803D; margin-top: 0; margin-bottom: 12px; display: flex; align-items: center; gap: 6px;">',
  '                  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>',
  '                  Para (Com a SAAM)',
  '                </h5>',
  '                <ul style="margin: 0; padding-left: 20px; font-size: 13px; color: #166534; line-height: 1.6;">',
  '                  <li>Auditoria antecipa riscos.</li>',
  '                  <li>Compliance protege o crescimento.</li>',
  '                  <li>Governança acelera decisões.</li>',
  '                  <li>O Fiscal previne problemas.</li>',
  '                  <li>Previsibilidade vale mais que velocidade.</li>',
  '                </ul>',
  '              </div>',
  '            </div>',
  '',
  '            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 24px; margin-top: 24px;">',
  '              <div>',
  '                <h4 style="color: #0F172A; border-bottom: 2px solid #E2E8F0; padding-bottom: 8px;">Nova Propriedade Intelectual</h4>',
  '                <div style="background: #EEF2FF; padding: 16px; border-radius: 8px; border: 1px solid #C7D2FE;">',
  '                  <h5 style="color: #4338CA; margin-top: 0;">MATRIZ DE PREVISIBILIDADE FISCAL</h5>',
  '                  <ul style="padding-left: 20px; margin-bottom: 0; font-size: 13px; color: #3730A3;">',
  '                    <li><strong>Nível 1 (Reativo):</strong> Problemas descobertos após impacto.</li>',
  '                    <li><strong>Nível 2 (Monitorado):</strong> Controles básicos e conferências.</li>',
  '                    <li><strong>Nível 3 (Preventivo):</strong> Ação antes das entregas.</li>',
  '                    <li><strong>Nível 4 (Preditivo):</strong> IA e antecipação de cenários.</li>',
  '                  </ul>',
  '                  <h5 style="color: #4338CA; margin-top: 16px;">MÉTODO P.R.E.V.E.R.</h5>',
  '                  <p style="font-size: 13px; color: #3730A3; margin: 0; font-family: monospace;">',
  '                    <strong>P</strong>erceber > <strong>R</strong>econhecer > <strong>E</strong>struturar > <strong>V</strong>alidar > <strong>E</strong>liminar > <strong>R</strong>evisar',
  '                  </p>',
  '                </div>',
  '              </div>',
  '              ',
  '              <div>',
  '                <h4 style="color: #0F172A; border-bottom: 2px solid #E2E8F0; padding-bottom: 8px;">A Jornada em 4 Capítulos</h4>',
  '                <ul style="list-style-type: none; padding: 0; font-size: 14px; color: #475569;">',
  '                  <li style="margin-bottom: 8px;"><strong>Capítulo 1: O Custo dos Riscos Invisíveis</strong> (Consciência do erro)</li>',
  '                  <li style="margin-bottom: 8px;"><strong>Capítulo 2: Prevenção</strong> (Checklists e Padronização)</li>',
  '                  <li style="margin-bottom: 8px;"><strong>Capítulo 3: Previsibilidade</strong> (Dados e IA)</li>',
  '                  <li><strong>Capítulo 4: Governança</strong> (Proteção e Planejamento para 2027)</li>',
  '                </ul>',
  '                ',
  '                <h4 style="color: #0F172A; border-bottom: 2px solid #E2E8F0; padding-bottom: 8px; margin-top: 16px;">Séries Fixas</h4>',
  '                <div style="display: flex; flex-wrap: wrap; gap: 8px;">',
  '                  <span style="background: #E2E8F0; padding: 4px 10px; border-radius: 4px; font-size: 11px; font-weight: 700; color: #475569;">Radar de Riscos</span>',
  '                  <span style="background: #E2E8F0; padding: 4px 10px; border-radius: 4px; font-size: 11px; font-weight: 700; color: #475569;">O Risco Invisível</span>',
  '                  <span style="background: #E2E8F0; padding: 4px 10px; border-radius: 4px; font-size: 11px; font-weight: 700; color: #475569;">Compliance na Prática</span>',
  '                  <span style="background: #E2E8F0; padding: 4px 10px; border-radius: 4px; font-size: 11px; font-weight: 700; color: #475569;">O Erro que Quase Aconteceu</span>',
  '                </div>',
  '              </div>',
  '            </div>',
  '            ',
  '          </div>',
  '        </details>'
].join('\\n');

let html = fs.readFileSync('index.html', 'utf-8');

const blockToFind = /<h3 style="color: #EA580C; margin: 0; font-size: 22px; font-weight: 800;">OUTUBRO 2026: A REVOLUÇÃO DOS DADOS FISCAIS<\/h3>[\s\S]*?<\/div>/;
const match = html.match(blockToFind);
if (match) {
    html = html.replace(match[0], match[0] + '\\n' + novemberHTML);
    fs.writeFileSync('index.html', html, 'utf-8');
    console.log('November campaign injected successfully into index.html');
} else {
    console.log('Could not find October block to append to.');
}
